name: build-test

on:
  workflow_dispatch: 
  pull_request:
  push:
    paths-ignore: [ "README.md" ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        lazarus-versions: ["dist", "stable"]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@master
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "LNet0.6.6.0"
        with-cache: false

    - name: Build the Main Application (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: lazbuild -B "src/librtlsdr_wincontrol.lpi"

    - name: Build the Main Application (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: lazbuild  "src/librtlsdr_wincontrol.lpi"
#        echo Installing Qt5 Dev
#        sudo apt update
#        sudo apt install libqt5pas-dev -y
#        echo Building with Qt5
#        lazbuild -B --bm=Release --ws=qt5 "src/librtlsdr_wincontrol.lpi"

    - name: Build the Main Application (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: lazbuild -B --bm=Release --ws=cocoa "src/librtlsdr_wincontrol.lpi"

    - name: Build the Unit Tests Application
      run: lazbuild -B --bm=Release "tests/testconsoleapplication.lpi"

    - name: Run the Unit Tests Application
      run: bin/testconsoleapplication "--all" "--format=plain"
